#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    auto_disable_touchpad = false
    filetree_direction = "left"
    filemanager = "defx"
    enable_statusline_bfpath = true
    enable_neomake = false
    enable_ale = true
    bootstrap_before = "myspacevim#before"
    
# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
autocomplete_method = "coc"
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#java"
[[layers]]
name = "lang#javascript"
auto_fix = true
enable_flow_syntax = true

[[layers]]
  name = "lang#typescript"

[[layers]]
name = "lang#dockerfile"

[[layers]]
name = "git"
default_position = 'bottom'

[[layers]]
  name = "colorscheme"
[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "denite"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#python"
 
[[layers]]
  name = 'lsp'
  filetypes = [
    "typescript",
    "javascript"
  ]

[[layers]]
  name = "lang#extra"

[[layers]]
  name = "denite"
[[layers]]
  name = "gtags"
  gtagslabel = "pygments"

[[layers]]
  name = "lang#kotlin"

[[custom_plugins]]
name = 'hashivim/vim-terraform'

[[custom_plugins]]
name = 'mxw/vim-jsx'

[[custom_plugins]]
name = 'juliosueiras/vim-terraform-completion'

